### PR TITLE
Fix issue 11: Fix setting of the atom charge according to the atom charge state (independent of Ewald summation)

### PR DESCRIPTION
**Pull request by chza**
## What was changed:
------------------------
- So far, the atom charge `az(1:na)` was only changed for systems, in which Ewald summation was used to calculate the long-range part of the electrostatic potential (The change of the atom charge `az` is needed to use Ewald summation in titrating systems).
- This lead to a miscalculation of the fractional charges in subroutine `ChargeAver` for titrating systems, in which Ewald summation was not enabled.
- This problem was fixed by always synchronizing the atom charge state `laz(1:na)` and the atom charge `az(1:na)`, independent of the usage of Ewald summation.

## What was tested:
--------
- The compilation with `mode=warn` does not trigger any warnings (ifort and gfortran)
- Clean run when running a test simulation with compilation in `mode=debug`
- The code runs in parallel
- Running the Testin procedure, an empty `diff.out` was obtained
- The version number was changed to 4.6.1 according to [Semantic Versioning](http://semver.org/)

Fixes Issue #11

### CODE REVIEW

**Review by thepith — APPROVED** [review]
Looks great.

✨ Can you add a test input?

**Comment by thepith** [comment]
Sorry, I thought that there was no test input having the ChargeAverage at all, but I just looked for the wrong string.

Anyways, there is already an input file with disabled ewald and weak charges. (`pe.mc.weakcharge.out`). Could we perhaps have it produce an average charge different than 0? This would then make a test input for the case of weak charges without ewald.

I just feel, that somehow covering as much as possible in the tests will help to avoid any bugs in the future. I would not only add new test inputs for new features, but have it in such a way that we would detect it if the same bug appears again.

But my comment is with :sparkles: : I don't mind if you don't incorporate it.

**Comment by thepith** [comment]
Why does the test output of `lysozyme.mc.weakcharge` not change with this bugfix?

**Comment by chza** [comment]
It doesn't change, because the malfunction ocurred only when these kind of systems were restartet with `txstart='setconf'`.

**Comment by thepith** [comment]
But `lysozyme.mc.weakcharge` has `txstart='setconf'`.

**Comment by chza** [comment]
Yes, I know - See my edited comment above ;-)

**Comment by chza** [comment]
The actual bug here was, that when restarting one of these systems with `txstart='continue'`, the current charge state `laz` of all atoms was read from `FCNF` and the atom charge `az` was set correspondingly **independent** of the state of `lewald`. When the simulation proceeded, only `laz` was changed during the charge change move, but `az` was left untouched, as long as `lewald=.false.`. Therefore it occurred, that atoms had `laz == .true.`, but still `az = 0.0`. This resulted in a flawed sampling of the charges in `ChargeAver`.

**Comment by chza** [comment]
Basically there were two ways to resolve this issue: Either, the atom charge `az` is synchronized with `laz` in `IOCnf` only if `lewald==.true.`, or the atom charge is always synchronized, independent of `lewald`. I chose the second strategy, because I preferred reducing the number of special cases with a need for consideration for further implementations.

**Comment by thepith** [comment]
Ok, now I understand. No wonder it took so long to spot the bug!

So would it be feasible to have a Testin file, which has weak charges, no ewald and use continue?

**Comment by chza** [comment]
Yes, sure! I won't add another input file, but I will change the Testin procedure such, that `lysozyme.weakcharge.mc` is restarted with `txstart='continue'` after running it with `txstart='setconf'`. As far as I remember we already have this kind of case in our Testin, correct?

**Comment by thepith** [comment]
Great! I just tried running `lysozyme.mc.weakcharge2` with the old molsim version, and got different results as when running with your improved version, which shows that your bugix is represented in the Testin. :smile:

**Comment by chza** [comment]
Alright! Then I'll finalize the pull request! 😃

**Pull request merged**
